config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
get 'notifications', :to => "notifications#index"
put 'notifications', :to => "notifications#update"

app/models/notification_config.rb
class NotificationConfig < ActiveRecord::Base
  unloadable

  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  unloadable
  
  before_filter :find_project, :authorize, :create_config_if_not_exists, :only => [:index]
  
  def index
    
   
  end

  def update
    @config = NotificationConfig.find_by_project_id(params[:notification_config][:project_id])
    @config.update_attributes(params[:notification_config])

    respond_to do |format|
      format.html{redirect_to ({:project_id => params[:notification_config][:project_id]}), :notice => l(:success_config_save)}
    end

  end




  private

  def find_project
    # @project variable must be set before calling the authorize filter
    @project = Project.find(params[:project_id])
  end

  def create_config_if_not_exists
    @config = NotificationConfig.find_by_project_id(@project.id)
    if @config.blank?
      @config = NotificationConfig.create(:project_id => @project.id)
    end
    

  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<h2><%= l(:campfire_notifications_title)%></h2>
<%= form_for @config, :url => notifications_path, :method => :put do |f|%>
  <div class="box tabular">
    <p>
      <label for="notification_config_token"><%= l(:label_token) %></label>
      <%= f.text_field :token %>
    </p>
    <p>
      <label for="notification_config_room"><%= l(:label_room) %></label>
      <%= f.text_field :room %>
    </p>
    <p>
      <label for="notification_config_subdomain"><%= l(:label_subdomain) %></label>
      <%= f.text_field :subdomain %>
    </p>
  </div>
  <%= f.hidden_field :project_id %>
  <%= submit_tag l(:button_save) %>
<% end %>